/********************************************************************
* MCA_dataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error MCA_dataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMCA_dataDict();
extern void G__cpp_setup_inheritanceMCA_dataDict();
extern void G__cpp_setup_typetableMCA_dataDict();
extern void G__cpp_setup_memvarMCA_dataDict();
extern void G__cpp_setup_globalMCA_dataDict();
extern void G__cpp_setup_memfuncMCA_dataDict();
extern void G__cpp_setup_funcMCA_dataDict();
extern void G__set_cpp_environmentMCA_dataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MCA_data.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MCA_dataDictLN_TClass;
extern G__linked_taginfo G__MCA_dataDictLN_TBuffer;
extern G__linked_taginfo G__MCA_dataDictLN_TMemberInspector;
extern G__linked_taginfo G__MCA_dataDictLN_TObject;
extern G__linked_taginfo G__MCA_dataDictLN_TNamed;
extern G__linked_taginfo G__MCA_dataDictLN_TString;
extern G__linked_taginfo G__MCA_dataDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__MCA_dataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MCA_dataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MCA_dataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__MCA_dataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MCA_dataDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__MCA_dataDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__MCA_dataDictLN_TH1D;
extern G__linked_taginfo G__MCA_dataDictLN_TH1I;
extern G__linked_taginfo G__MCA_dataDictLN_TGraphErrors;
extern G__linked_taginfo G__MCA_dataDictLN_MCA_data;
extern G__linked_taginfo G__MCA_dataDictLN_CalMCA_data;
extern G__linked_taginfo G__MCA_dataDictLN_SourceData;
extern G__linked_taginfo G__MCA_dataDictLN_GeCalibrate;
extern G__linked_taginfo G__MCA_dataDictLN_vectorlESourceDatamUcOallocatorlESourceDatamUgRsPgR;
extern G__linked_taginfo G__MCA_dataDictLN_reverse_iteratorlEvectorlESourceDatamUcOallocatorlESourceDatamUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MCA_dataDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__MCA_dataDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MCA_dataDictLN_IsotopeDB;
extern G__linked_taginfo G__MCA_dataDictLN_Isotope;
extern G__linked_taginfo G__MCA_dataDictLN_vectorlEIsotopecOallocatorlEIsotopegRsPgR;
extern G__linked_taginfo G__MCA_dataDictLN_reverse_iteratorlEvectorlEIsotopecOallocatorlEIsotopegRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
