// Root file generator from IEC files generated by the Lynx/Maestro package. 
//
// Carsten Krauss 2007, 2008, 2009, 2010, 2011
//


#include "iostream"
#include "fstream"

#include "time.h"
#include "TH1I.h"
#include "TNamed.h"
#include "TCanvas.h"
#include "TFile.h"

#include "MCA_data.h"

using namespace std;


int main(int argc, char **name){

  if (argc<2) {
    cerr << " give argument!" << endl;
    return -1;
  }
  MCA_data *dat = new MCA_data();
  if (dat->Read(name[1])==0){
    TFile y(TString(dat->GetOutputFilename()),"recreate");
    dat->Write();
    y.Close();
  }
  else{
    cout << "Problem while reading the data." << endl;
  }
  return 0;
}
